[tool.poetry]
name = "expense-tracker"
version = "0.1.0"
description = ""
authors = ["Puneeth Chaganti <punchagan@muse-amuse.in>"]

[tool.poetry.dependencies]
python = "^3.8"
seleniumbase = "^4.4.4"
pytest = "^7.1.3"
pytest-parallel = "^0.1.1"
pandas = "^1.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
