"""add tag many-to-many

Revision ID: 4b6790846b03
Revises: 9befc1f324c4
Create Date: 2022-10-20 15:20:45.107021

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4b6790846b03"
down_revision = "9befc1f324c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expense_tag",
        sa.Column("expense_id", sa.String(length=40), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expense.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("expense_id", "tag_id"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expense_tag")
    op.drop_table("tag")
    # ### end Alembic commands ###
