"""make category relation many-to-one

Revision ID: 9befc1f324c4
Revises: 0a755389be4c
Create Date: 2022-10-20 13:23:39.380082

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9befc1f324c4"
down_revision = "0a755389be4c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expense_category")
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "category-expense-foreign-key", "category", ["category_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.drop_constraint("category-expense-foreign-key", type_="foreignkey")
        batch_op.drop_column("category_id")

    op.create_table(
        "expense_category",
        sa.Column("expense_id", sa.VARCHAR(length=40), nullable=False),
        sa.Column("category_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expense.id"],
        ),
        sa.PrimaryKeyConstraint("expense_id", "category_id"),
    )
    # ### end Alembic commands ###
